### ISSUE TITLE
On-Demand VM Provisioning

### ISSUE THREAD

**Issue by dhiru1602** [SEI-AMS/pycloud#2]
Does pycloud support On-Demand VM Provisioning so that the mobile device can create Service VM's  on the Cloudlet Server based on the requirement? Instead of having pre-defined services in the Cloudlet Server, it is possible for the mobile device or a client to deploy a Service on the Cloudlet Server based on it's need, possibly by the usage of VM-Overlays?

This is more like a question rather than an issue.

**Comment by jdroot** [comment]
Hi dhiru1602!

Pycloud has not supported On-Demand VM Provisioning for about 18 months because the focus of the groups research had moved away from it. In our testing, we found that that On-Demand VM Provisioning took a while (transferring a whole VM) and drained a noticeable amount of battery (from the transfer). Due to this, the focus moved to having the VMs pre-provisioned on the server. I think it could be worth re-evaluating with newer technologies such as [MarageOS](https://mirage.io/) or [OSv](http://osv.io/). Both of these OSes are standalone and orders of magnitude smaller on disk than the old On-Demand VM Provisioning approach.

**Comment by dhiru1602** [comment]
Thanks for the clarification James!
